spring:
  application:
    name: Auth-application
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9091

jwt:
  secret: secretkey
  expiration: 86400000